@startuml ScheduleLog

package assets {
}

package docs {
}

package schedulelog {
    package config {
        [checkstyle]
        [spotbugs]
    }
    package core {
        [Activity]
        [Courses]
        [Subject]
        [FileStorage]
        [RestConsumer]

    }
    package rest {
        [Controller]
        [RestApplication]
    }
    package ui {
        [App]
        [AppController]
    }
}
rest -[hidden]-> core
rest .down.> core : uses

ui -[hidden]-> core
ui .down.> core : uses
@enduml