@startuml

component core {
	package todolist.core
	package todolist.json
}

todolist.core ..> todolist.json
component jackson {
}

todolist.json ..> jackson

component fxutil {
}

component fxui {
	package todolist.ui
	package todolist.ui.util
}

todolist.ui ..> todolist.ui.util
todolist.ui ..> todolist.core
todolist.ui ..> todolist.json

component javafx {
	component fxml {
	}
}

fxui ..> javafx
fxui ..> fxml
fxui ..> fxutil

component jaxrs {
}

component rest {
	package todolist.restapi
	package todolist.restserver
}

rest ..> jaxrs

todolist.restapi ..> todolist.core

todolist.restserver ..> todolist.core
todolist.restserver ..> todolist.json
todolist.restserver ..> todolist.restapi

component jersey {
}

component grizzly2 {
}

rest ..> jersey
rest ..> grizzly2

@enduml